on:
  release:
    types: [created]

jobs:
  release:
    environment: GIT_TOKEN
    name: release ${{ matrix.target }}  (with non-required env)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            env:
                TARGET: x86_64-apple-darwin
                COMPILER: clang
                LINKER: clang

          - os: ubuntu-latest
            env:
                TARGET: armv7-unknown-linux-musleabihf
                COMPILER: arm-linux-gnueabihf-gcc-5
                LINKER: gcc-5-arm-linux-gnueabihf

          - os: ubuntu-latest
            env:
                TARGET: x86_64-unknown-linux-musl
                COMPILER: gcc
                LINKER: gcc
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-linux-musl
            archive: tar.gz
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: "."
          ARCHIVE_TYPES: ${{ matrix.archive }}
  release_without_not_required:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
