name: Build Binaries
on: 
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  build_for_mac:
    name: MacOS
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/lorsrf lorsrf-macos64
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          curl \
            -f \
            -sSL \
            -XPOST \
            -H "Authorization: token $GIT_TOKEN" \
            -H "Content-Length: $(stat -f%z lorsrf-macos64)" \
            -H "Content-Type: application/octet-stream" \
            --upload-file "lorsrf-macos64" \
            "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)/assets?name=lorsrf-macos64"
  build_for_pi:
    name: Raspberry Pi
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf
      - name: Rename binary
        run: mv target/armv7-unknown-linux-gnueabihf/release/lorsrf lorsrf-armv7-pi
      - name: Upload to release
        uses: JasonEtco/upload-to-release@d648f1babf776de9cad881320bd9e9818fc3b262
        with:
          args: lorsrf-armv7-pi application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
  
  build_for_linux:
    name: Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Rename binary
        run: mv target/release/lorsrf lorsrf-linux-amd64
      - name: Upload to release
        uses: JasonEtco/upload-to-release@d648f1babf776de9cad881320bd9e9818fc3b262
        with:
          args: lorsrf-linux-amd64 application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
